### ISSUE TITLE
Shebang: why avoid #!/usr/bin/env perl and #!perl?

### ISSUE THREAD

**Issue by cxw42** [perlpunk/perl5-module-meta#7]
Tina, CXW here - thanks for putting this list together!  This issue is a request for additional explanation.

The [shebang section](https://github.com/perlpunk/perl5-module-meta/blob/24f4ddc3e698ad643329667fd9bc1ea0fd00ab06/README.md#shebang) suggests `#!/usr/bin/perl`.  How does this interact with perlbrew?  [Perlbrew](https://perlbrew.pl/Dealing-with-shebangs.html), at the bottom of the page, says `env` is probably OK, except for CentOS.

I see that Perl-Toolchain-Gang/ExtUtils-MakeMaker#58 discusses shebang-rewriting, and that `env` currently isn't rewritten.  Is that the main reason for sticking with `/usr/bin/perl`?  Are there other factors to be aware of, especially if they affect future portability?

Would you be willing to expand the document a bit to explain the reasons, or to clarify that EUMM rewriting is the reason?  Thank you for considering this request!

**Comment by perlpunk** [comment]
Yes, the reason is that `env perl` is not rewritten. Only if the program ends with `perl` it is rewritten.
I can add an explanation, and also link to the issue, thanks =)

**Comment by perlpunk** [comment]
I added an explanation
